Release: Classic Coins v0.0.1

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -6,6 +6,8 @@ name: build-package.yml
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
+    branches:
+    - main
     tags:
       - v*
       - Release
@@ -27,6 +29,19 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
+      
+      
+      - name: Get tag names
+        id: tag_names
+        if: startsWith(github.ref, 'refs/tags/')
+        run: echo "::set-output name=names::$(echo ${{ github.ref }} | cut -d/ -f3-)"
+
+      - name: Check tags
+        run: |
+          if [[ "${{ github.ref }}" != *"v"* && "${{ github.ref }}" != "Release" && "${{ github.ref }}" != "Pre-Release" && "${{ github.ref }}" != "Build" && "${{ github.ref }}" != "Test" ]]; then
+            echo "Required tags not found"
+            exit 1
+          fi
 
       -   name: Get project name
           id: project_name
@@ -37,10 +52,6 @@ jobs:
             project_name=$(echo "$commit_message" | grep -oP '(?<=Update: )[^\s]*')
             fi
             echo "::set-output name=name::$project_name"
-            
-      -   name: Get tag name
-          id: tag_name
-          run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/tags/})"
 
       # Runs a single command using the runners shell
       - name: Archive Release
