Release: Classic Coins v0.0.1

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -21,7 +21,7 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
-  checks:
+  check:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -29,45 +29,57 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
-
-      - name: Get tag names
-        id: tag_names
-        run: |
-          commit_message="${{ github.event.head_commit.message }}"
-          tag_name=$(echo "$commit_message" | grep -oP '(?<=Release: |Pre-Release: )v?\d+\.\d+\.\d+')
-          if [ -z "$tag_name" ]; then
-            tag_name=$(echo "$commit_message" | grep -oP '(?<=Update: )v?\d+\.\d+\.\d+')
-          fi
-          echo "TAG_NAMES=$tag_name" >> $GITHUB_ENV
           
-      - name: Check tags
+      - name: Extract commit message
+        id: extract_commit_message
+        if: success()
         run: |
-          if [[ "${{ env.TAG_NAMES }}" != "Release" && "${{ env.TAG_NAMES }}" != "Pre-Release" ]]; then
-            echo "Required tags not found"
-            exit 1
+          COMMIT_MESSAGE=${{ github.event.head_commit.message }}
+          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
+
+      - name: Check tags
+        id: check_tags
+        if: success()
+        run: |
+          if [[ ${{ env.COMMIT_MESSAGE }} =~ (v\*|Release|Pre-Release|Build|Test) ]]; then
+            echo "TAGS_PRESENT=true" >> $GITHUB_ENV
+          else
+            echo "TAGS_PRESENT=false" >> $GITHUB_ENV
           fi
           
       - name: Get project name
-        id: project_name
+        id: get_name
         if: success()
         run: |
-          commit_message="${{ github.event.head_commit.message }}"
-          project_name=$(echo "$commit_message" | grep -oP '(?<=Release: )[^\s]*')
-          if [ -z "$project_name" ]; then
-            project_name=$(echo "$commit_message" | grep -oP '(?<=Update: )[^\s]*')
-          fi
-          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
-          if [ -z "$project_name" ]; then
-            echo "Project name not found"
+          # Extract project name from repository context
+          PROJECT_NAME=${{ github.repository }}
+
+          # Format project name
+          PROJECT_NAME=${PROJECT_NAME,,}   # Convert to lowercase
+          PROJECT_NAME=${PROJECT_NAME// /-} # Replace spaces with hyphens
+
+          # Set environment variable
+          echo "FORMATTED_PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
+          
+      -  name: Extract version number
+         id: get_version
+         if: success()
+         run: |
+           # Extract version number from commit message
+           if [[ ${{ env.COMMIT_MESSAGE }} =~ ^Release:\ (.+)\ v(.+)$ ]]; then
+             echo "VERSION_NUMBER=${BASH_REMATCH[2]}" >> $GITHUB_ENV
+           else
+            echo "Invalid commit message format"
             exit 1
-          fi
+           fi
           
   # This workflow contains a single job called "build"
-  build-package:
+  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
+    if: ${{ env.TAGS_PRESENT == 'true' }}
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
@@ -76,17 +88,24 @@ jobs:
       - name: Archive Release
         uses: thedoctor0/zip-release@0.7.1
         with:
-          path: classic-coins/
+          path: ${{ env.PROJECT_NAME }}/
           type: zip
-          filename: release.zip
+          filename: ${{ env.PROJECT_NAME }}-${{ env.VERSION_NUMBER }}.zip
           exclusions: '*.git* /*node_modules/* .editorconfig'
+          
+      - name: Exit
+        if: ${{ env.TAGS_PRESENT != 'true' }}
+        run: |
+          echo "Tags are not present in the commit message"
+          exit 1
 
   # This workflow contains a single job called "build"
-  upload-package:
+  upload:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
+    
     # Steps represent a sequence of tasks that will be executed as part of the job
+    if: success()
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
@@ -96,4 +115,4 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: release-artifact
-          path: release.zip
+          path: ${{ env.PROJECT_NAME }}-${{ env.VERSION_NUMBER }}.zip
