Update build-package.yml

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -30,20 +30,39 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      -  name: Get project name
-         id: project_name
-         run: |
-           commit_message="${{ github.event.head_commit.message }}"
-           project_name=$(echo "$commit_message" | grep -oP '(?<=Release: )[^\s]*')
-           if [ -z "$project_name" ]; then
-           project_name=$(echo "$commit_message" | grep -oP '(?<=Update: )[^\s]*')
-           fi
-           echo "::set-output name=name::$project_name"
-
       - name: Get tag names
         id: tag_names
-        run: echo "::set-output name=names::$(echo ${{ github.ref }} | cut -d/ -f3-)"
-
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          commit_message="${{ github.event.head_commit.message }}"
+          tag_name=$(echo "$commit_message" | grep -oP '(?<=Release: |Pre-Release: )v?\d+\.\d+\.\d+')
+          if [ -z "$tag_name" ]; then
+            tag_name=$(echo "$commit_message" | grep -oP '(?<=Update: )v?\d+\.\d+\.\d+')
+          fi
+          echo "TAG_NAMES=$tag_name" >> $GITHUB_ENV
+          
+      - name: Check tags
+        run: |
+          if [[ "${{ env.TAG_NAMES }}" != "Release" && "${{ env.TAG_NAMES }}" != "Pre-Release" ]]; then
+            echo "Required tags not found"
+            exit 1
+          fi
+          
+      - name: Get project name
+        id: project_name
+        if: success()
+        run: |
+          commit_message="${{ github.event.head_commit.message }}"
+          project_name=$(echo "$commit_message" | grep -oP '(?<=Release: )[^\s]*')
+          if [ -z "$project_name" ]; then
+            project_name=$(echo "$commit_message" | grep -oP '(?<=Update: )[^\s]*')
+          fi
+          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
+          if [ -z "$project_name" ]; then
+            echo "Project name not found"
+            exit 1
+          fi
+          
       # Runs a single command using the runners shell
       - name: Archive Release
         uses: thedoctor0/zip-release@0.7.1
